#\DeclareLyXModule{twn(tip/warning/notice)}
#DescriptionBegin
# To insert a tip/warning/notice environment.
#DescriptionEnd
# Author : Su Baochen<subaochen@126.com>

Format 49

InsetLayout 	Flex:Note
LyXType 	custom
Labelstring    	Note
Decoration  	classic
LabelFont
  Color   	collapsable
  Size    	Small
EndFont
MultiPar    	true
LatexName   	Note
LatexType   	Environment
Preamble

  \usepackage{tikz}
  \usepackage{color}
  \usepackage[framemethod=tikz]{mdframed}
  \usetikzlibrary{calc}
  \usepackage{fourier-orns}
  \definecolor{noteColor}{named}{green}%TODO：图书往往是黑白印刷的，颜色不利于将来出版
\tikzset{
    notesymbol/.style={
        rectangle,
        draw=noteColor,
        fill=white,
        scale=1,
        overlay}
}
\global\mdfdefinestyle{note}{%
  hidealllines=true,leftline=true,
  skipabove=12,skipbelow=12pt,
  innertopmargin=0.4em,%
  innerbottommargin=0.4em,%
  innerrightmargin=0.7em,%
  rightmargin=0.7em,%
  innerleftmargin=1.7em,%
  leftmargin=0.7em,%
  middlelinewidth=.2em,%
  linecolor=noteColor,%
  fontcolor=noteColor,%
  firstextra={\path let \p1=(P), \p2=(O) in ($(\x2,0)+0.5*(0,\y1)$)
       node[notesymbol] {\danger};},%
  secondextra={\path let \p1=(P), \p2=(O) in ($(\x2,0)+0.5*(0,\y1)$)
       node[notesymbol] {\danger};},%
  middleextra={\path let \p1=(P), \p2=(O) in ($(\x2,0)+0.5*(0,\y1)$)
       node[notesymbol] {\danger};},%
  singleextra={\path let \p1=(P), \p2=(O) in ($(\x2,0)+0.5*(0,\y1)$)
       node[notesymbol] {\danger};}%
 }

\newmdenv[style=note]{Note}

EndPreamble
End

