#\DeclareLyXModule{twn(tip/warning/notice)}
#DescriptionBegin
# To insert a tip/warning/notice environment.
#DescriptionEnd
# Author : Su Baochen<subaochen@126.com>

Format 49

InsetLayout 	Flex:Notice
LyXType 	custom
Labelstring    	Notice
Decoration  	classic
LabelFont
  Color   	collapsable
  Size    	Small
EndFont
MultiPar    	true
LatexName   	notice
LatexType   	Environment
Preamble
  \usepackage{tikz}
  \usetikzlibrary{calc}
  \usepackage[framemethod=tikz]{mdframed}
  \usepackage{xcolor}
\tikzset{
warningsymbol/.style={
rectangle,draw=red,
fill=white,scale=1,
overlay}}

\mdfdefinestyle{warning}{%
hidealllines=true,leftline=true,
skipabove=12,skipbelow=12pt,
innertopmargin=0.4em,%
innerbottommargin=0.4em,%
innerrightmargin=0.7em,%
rightmargin=0.7em,%
innerleftmargin=1.7em,%
leftmargin=0.7em,%
middlelinewidth=.2em,%
linecolor=red,%
fontcolor=red,%
firstextra={\path let \p1=(P), \p2=(O) in ($(\x2,0)+0.5∗(0,\y1)$)
node[warningsymbol] {\$};},%
secondextra={\path let \p1=(P), \p2=(O) in ($(\x2,0)+0.5∗(0,\y1)$)
node[warningsymbol] {\$};},%
middleextra={\path let \p1=(P), \p2=(O) in ($(\x2,0)+0.5∗(0,\y1)$)
node[warningsymbol] {\$};},%
singleextra={\path let \p1=(P), \p2=(O) in ($(\x2,0)+0.5∗(0,\y1)$)
node[warningsymbol] {\$};},%
}

  \newenvironment{notice}{
    \begin{mdframed}[style=warning]
    \end{mdframed}
  }
EndPreamble
End

