#\DeclareLyXModule{Warning}
#DescriptionBegin
#Adds an environment for warning paragraphs.
#Warning paragraph is a paragraph in which the paragraph begin with a W on left .
#DescriptionEnd

#Author: subaochen <subaochen@126.com>
Format 49

Style Warning
LabelString "warning"
LatexType Environment
LatexName warningparagraph
Align Block
Margin Static
LeftMargin "MMMM"
ParIndent "MMMM"
Preamble
  \usepackage{tikz}
  \usepackage[x11names, svgnames]{xcolor}
  \usepackage[framemethod=tikz]{mdframed}
 % \usepackage{showexpl}
  \usetikzlibrary{calc}
  \usepackage{fourier-orns}
  \definecolor{warningColor}{named}{Red3}

\global\mdfdefinestyle{warning}{%
  hidealllines=true,leftline=true,
  skipabove=12,skipbelow=12pt,
  innertopmargin=0.4em,%
  innerbottommargin=0.4em,%
  innerrightmargin=0.7em,%
  rightmargin=0.7em,%
  innerleftmargin=1.7em,%
  leftmargin=0.7em,%
  middlelinewidth=.2em,%
  linecolor=warningColor,%
  fontcolor=warningColor,%
  firstextra={\path let \p1=(P), \p2=(O) in ($(\x2,0)+0.5*(0,\y1)$)
       node[warningsymbol] {\danger};},%
  secondextra={\path let \p1=(P), \p2=(O) in ($(\x2,0)+0.5*(0,\y1)$)
       node[warningsymbol] {\danger};},%
  middleextra={\path let \p1=(P), \p2=(O) in ($(\x2,0)+0.5*(0,\y1)$)
       node[warningsymbol] {\danger};},%
  singleextra={\path let \p1=(P), \p2=(O) in ($(\x2,0)+0.5*(0,\y1)$)
       node[warningsymbol] {\danger};},%
 }

\newmdenv[style=warning]{Warning}
EndPreamble
End

