#\DeclareLyXModule{note(tip/warning/notice)}
#DescriptionBegin
# To insert a tip/warning/notice environment.
#DescriptionEnd
# Author : Su Baochen<subaochen@126.com>

Format 49
AddToPreamble
\usepackage[framemethod=tikz]{mdframed}
\usetikzlibrary{calc,arrows}
\makeatletter
\mdf@do@stringoption{digressiontitle=={Info}}
\tikzset{
  excursus arrow/.style={%
      line width=2pt,
      draw=gray!40,
      rounded corners=2ex,
  },
  excursus head/.style={
      fill=white,
      font=\bfseries\sffamily,
      text=gray!80,
      anchor=base west,
  },
}
\mdfdefinestyle{digressionarrows}{%
   singleextra={%
            \path let \p1=(P), \p2=(O) in (\x2,\y1) coordinate (Q);
            \path let \p1=(Q), \p2=(O) in (\x1,{(\y1-\y2)/2}) coordinate (M);
            \path [excursus arrow, round cap-to]
                        ($(O)+(5em,0ex)$) -| (M) |- %
                        ($(Q)+(12em,0ex)$) .. controls +(0:16em) and +(185:6em) .. %
                        ++(23em,2ex);
            \node [excursus head] at ($(Q)+(2.5em,-0.75pt)$) {\mdf@digressiontitle};},
   firstextra={%
            \path let \p1=(P), \p2=(O) in (\x2,\y1) coordinate (Q);
            \path [excursus arrow,-to] (O) |- %
                        ($(Q)+(12em,0ex)$) .. controls +(0:16em) and +(185:6em) .. %
                        ++(23em,2ex);
            \node [excursus head] at ($(Q)+(2.5em,-2pt)$) {\mdf@digressiontitle};},
   secondextra={%
            \path let \p1=(P), \p2=(O) in (\x2,\y1) coordinate (Q);
            \path [excursus arrow,round cap-]($(O)+(5em,0ex)$) -| (Q);},
   middleextra={%
            \path let \p1=(P), \p2=(O) in (\x2,\y1) coordinate (Q);
            \path [excursus arrow](O) -- (Q);},
   middlelinewidth=2.5em,middlelinecolor=white,
   hidealllines=true,topline=true,
   innertopmargin=0.5ex,
   innerbottommargin=2.5ex,
   innerrightmargin=2pt,
   innerleftmargin=2ex,
   skipabove=0.87\baselineskip,
   skipbelow=0.62\baselineskip,
}
\makeatother

\newmdenv[style=digressionarrows,digressiontitle=Info]{info}
\newmdenv[style=digressionarrows,digressiontitle=Side note]{sidenote}

EndPreamble

InsetLayout 	Flex:MyNote
LyXType 	custom
Labelstring    	MyNote
Decoration  	classic
LabelFont
  Color   	collapsable
  Size    	Small
EndFont
MultiPar    	true
LatexName   	mynote
LatexType   	Environment
Preamble
\newenvironment{mynote}{
  \begin{info}
  \end{info}
}
EndPreamble
End

